# save-position-on-quit
--osd-font-size=18
--osd-level=3
osc=no
# hwdec: auto-safe

# === Video Output ===
vo=gpu-next
gpu-api=vulkan       # Recommended for Intel on Wayland.
hwdec=auto-safe      # Let MPV choose the best hardware decoder.

# === Scaling (Performance-focused) ===
# Start with simpler, faster algorithms.
# bicubic and lanczos are good balance. ewa_lanczossharp is more demanding.
#scale=spline36
#cscale=spline36

# === General Playback ===
# osc=yes                      # On-screen controller
save-position-on-quit=yes
keep-open=yes
fs=yes
#autofit=90%
#video-sync=display-resample  # Helps with judder, generally low cost on Wayland.

# === Cache ===
cache=yes
cache-default=500000

dither-depth=auto
deband=yes


